### ISSUE TITLE
SSL Check

### ISSUE THREAD

**Issue by obbyK** [marianobarrios/tls-channel#145]
I just finished testing something i built using this. Tried testing for a variety of scenarios and it seems that tlsChannel client doesn't check whether the server is speaking ssl. You can call `write` and it won't give you any error. In my case, it was the server closing the connection after a given timeout that stopped the client. otherwise it just doesn't return any error (in blocking mode).

**Comment by marianobarrios** [comment]
Hi Obby. Thanks for using the library and creating this issue. A [TLS handshake](https://www.cloudflare.com/learning/ssl/what-happens-in-a-tls-handshake/) is initiated by a client, that sends a `ClientHello` message, and then waits for the `ServerHello` one. If the server just reads the data and keeps silence, the only thing the client can do is just wait (until someone closes the connection due to some timeout).

Please note that writes in the socket interface will always return if there is enough buffer space; the function returning does not imply that any payload was sent. A big-enough write should block.

Please let me know if you think I am missing something.

 Best regards.
