### ISSUE TITLE
[Question] SNI settings for ClientTlsChannel?

### ISSUE THREAD

**Issue by igrishaev** [marianobarrios/tls-channel#269]
Hi First of all, thank you for the library! This is not an issue actually but rather a question about it.

I have a project that performs network communications throughout a bare Socket instance. There is also a thin wrapper with SSLSocket for those who enables SSL in settings.

Recently, I was thinking about switching to a SocketChannel class. Since Java lacks SSLSocketChannel, I've found this library through Google and StackOverflow.

My problem is the following: when using ClientTlsChannel with a Postgres server like this:

```java
final SocketAddress address = new InetSocketAddress(host, port);
SocketChannel sc = SocketChannel.open(address);

// now upgrade to SSL, if useSSL = true
SSLContext sslContext = SSLContext.getDefault();
channel = ClientTlsChannel.newBuilder(
                channel,
                sslContext
).build();
```

When reaching Postgres through that channel, it argues:

```
ERROR: The endpoint ID is not specified. Either upgrade the Postgres client library (libpq) 
for SNI support or pass the endpoint ID (the first part of the domain name) as a parameter: 
'&options=endpoint%3D'. See [https://neon.tech/sni](https://neon.tech/sni) for more information.
```

There is a special page on Neon.tech site describing this issue: https://neon.tech/docs/connect/connection-errors#the-endpoint-id-is-not-specified

Technically I know how to bypass it by adding this option:

```
.pgParam("options", "endpoint=ep-fancy-queen-a2kw7zqr")
```

But I'm still interested why doesn't it happen when using plain Socket and SSLSocket classes? Is there is a way to tackle this using your library?

Let me know if something is confusing, I'll try to make it clearer.

**Comment by marianobarrios** [comment]
Hi Ivan,

Thanks for using and testing the library.

Client-side SNI (that is, _sending_ the name) is done exclusively at the `SSLEngine` level. `TlsChannel` is completely agnostic about that. Some Googling shows that you can configure the name using [this method](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/javax/net/ssl/SSLParameters.html#setServerNames(java.util.List)), and then setting the parameters in the engine.

About why it worked using `SSLSocket`, I don't know. It's a completely different implementation, maybe it's automatic. Note: the comment about the `Socket` class confused me, because that class implements plain TCP and SNI is a TLS concept that does not exist in unencrypted sockets.

Hope this helps.

Best regards.

**Comment by igrishaev** [comment]
Dear @marianobarrios 

Thanks for you reply. Actually, the following lines have fixed the problem:

```java
final SSLContext sslContext = getSSLContext();
this.sslEngine = sslContext.createSSLEngine(getHost(), getPort());
this.sslEngine.setUseClientMode(true);
this.channel = ClientTlsChannel.newBuilder(channel, sslEngine).build();
```

So you were right: I produced an instance of SSLSession out from the context, and passed host and port, and it worked.

Thanks again, closing.
